[project]
name = "birthday-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hengamehznd", email = "162028907+Hengamehznd@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.17",
    "jdatetime>=6.1.0",
]

[project.scripts]
birthday-manager = "birthday_manager:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
