# Generated by Django 5.2.17 on 2026-09-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'ordering': ['birthday_date'], 'verbose_name': 'تولد', 'verbose_name_plural': 'تولدها'},
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday_date',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='relation',
            field=models.CharField(choices=[('FRIEND', 'دوست'), ('FAMILY', 'خانواده'), ('COLLEAGUE', 'همکار'), ('OTHER', 'سایر')], max_length=10, verbose_name='نسبت'),
        ),
    ]
